import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import CardDetail from '../components/Cards/Detail';
import Footer from '../components/Footers/Default';
import Navbar from '../components/Navbars/Default';
import PokemonList from '../components/Containers/PokemonList';
import { getPokemon } from '../services/api/pokedex';
const publicApi = process.env.NEXT_PUBLIC_PUBLIC_API;

export default function Home({ listPokemons, defaultPokemon }) {
    const [selectedPokemon, setSelectedPokemon] = useState(null);

    const changeSelectedPokemon = async (id) => {
        try {
            const res = await getPokemon(id);
            if (res.data) {
                res.data.image = `https://pokeres.bastionbot.org/images/pokemon/${res.data.id}.png`;
                window.scrollTo(0, 0);
                setSelectedPokemon(res.data);
            }
        } catch (error) {}
    };

    return (
        <div style={{ backgroundColor: '#f8f8f8' }}>
            <Navbar changeSelectedPokemon={changeSelectedPokemon}></Navbar>
            <div>
                <img src="/img/logotext.png" width="200px" className="mx-auto mt-20" alt="" />
                <CardDetail defaultPokemon={defaultPokemon} selectedPokemon={selectedPokemon}></CardDetail>
                <div className="container mx-auto">
                    <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                </div>
                <PokemonList data={listPokemons} changeSelectedPokemon={changeSelectedPokemon}></PokemonList>
            </div>
            <Footer></Footer>
        </div>
    );
}

export const getStaticProps = async () => {
    const listPokemons = await fetch(`${publicApi}pokemon`).then((response) => response.json());
    const defaultPokemon = await fetch(`${publicApi}pokemon/25`).then((response) => response.json());
    if (listPokemons?.results) {
        listPokemons.results.forEach((el, index) => {
            el.image = `https://pokeres.bastionbot.org/images/pokemon/${index + 1}.png`;
        });
    }
    if (defaultPokemon) {
        defaultPokemon.image = `https://pokeres.bastionbot.org/images/pokemon/25.png`;
    }
    return {
        props: { listPokemons, defaultPokemon },
    };
};
